### ISSUE TITLE
Drink SWA Checkout not working Issue

### ISSUE THREAD

**Issue by Akdex** [farzi-engineer/farzicom-roadmap#1]
![DrinkSWA oreder placing issue ](https://user-images.githubusercontent.com/49723359/147094386-25a99cac-e3c0-4e13-adae-1e909d2bab77.PNG)

Taking Longer time than usual

**Comment by deathping1994** [comment]
Whats the reason? can you check the console and share the response ? that can help diagnose the problem.

**Comment by soham2710** [comment]
The website hanged out and on checking out the cart it took longer time to load. Hence we reported the issue.

**Comment by deathping1994** [comment]
Closing since it's not reproducible. Feel free to open the issue again if the issue is replicable.
